server:
  port: 30000

spring:
  application:
    name: ludo-backend
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect